In [3]:
import re
import csv
import time
from bs4 import BeautifulSoup
import requests
import pandas as pd
import os
from datetime import datetime
from nltk.corpus import stopwords
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException

In [493]:
def Origin(Name):
    
    driver = webdriver.Chrome('/home/erq/chromedriver')

    url = f'https://www.misapellidos.com/buscar.php?busqueda=combinada&texto={Name}&buscar=Buscar'
    driver.get(url)       

    time.sleep(2)
    driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table/tbody/tr[2]/td[1]/table[2]/tbody/tr[1]/td[2]/img').text

    html_from_page = driver.page_source
    soup = BeautifulSoup(html_from_page, 'html.parser')
    driver.close() 

    apellidos_encontrados = (soup.find_all('td', attrs ={'width':'565'}))
    Origin = ""
    for i in range(len(apellidos_encontrados)):
        match = (soup.find_all('td', attrs ={'width':'565'})[i].text.split(' Breve Descripción de ')[1])
        print(match)
        if match == Name.capitalize():
    
            Origin = soup.find_all('td', attrs ={'width':'85'})[i].find_next('img').find_next('img').get('src').split('/')[-1].split('.')[0].capitalize()
            print(match, '----->', Origin)
            break
        elif match.capitalize() == Name.capitalize():
            Origin = soup.find_all('td', attrs ={'width':'85'})[i].find_next('img').find_next('img').get('src').split('/')[-1].split('.')[0].capitalize()
            print(match, '----->', Origin)
            break
        else:
            pass
            print('No es el primero')
    if Origin == "":
        print('Origin not found for', Name)
        
    return(Origin)

In [941]:
def Surname_Data(Name):
    from selenium.webdriver.common.keys import Keys
    driver = webdriver.Chrome('/home/erq/chromedriver')

    url = 'https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736177009&menu=resultados&secc=1254736195497&idp=1254734710990'
    
    #url = 'https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736177009&menu=resultados&secc=1254736195454&idp=1254734710990'
    driver.get(url)       

    time.sleep(2)
    try:
        driver.find_element_by_xpath('/html/body/div[10]/div[1]/button/span[1]').click()

    except: 
         pass
    apellido = driver.find_element_by_id('cmb6')

    apellido.clear()
    apellido.send_keys(Name)

    # cookies
    driver.find_element_by_xpath('/html/body/div[6]/div/div[2]/a[2]').click()
    time.sleep(1)

    # next page
    driver.find_element_by_xpath('//*[@id="tapellidos1"]/p[2]/button[2]').click()

    time.sleep(2)

    hannnnndle = []
    for handle in driver.window_handles:
        hannnnndle.append(handle)
    
    time.sleep(2)

    driver.switch_to.window(driver.window_handles[1])

    html_from_page = driver.page_source
    soup = BeautifulSoup(html_from_page, 'html.parser')

    driver.quit() 
    tables = pd.read_html(html_from_page)
    Tabla  = tables[4]
    return(Tabla)

In [945]:
def Name_Data(Name):
    from selenium.webdriver.common.keys import Keys
    driver = webdriver.Chrome('/home/erq/chromedriver')
    
    url = 'https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736177009&menu=resultados&secc=1254736195454&idp=1254734710990'
    driver.get(url)       

    time.sleep(2)
    try:
        driver.find_element_by_xpath('/html/body/div[10]/div[1]/button/span[1]').click()

    except: 
         pass
        
    apellido = driver.find_element_by_id('cmb6')

    apellido.clear()
    apellido.send_keys(Name)

    # cookies
    driver.find_element_by_xpath('/html/body/div[6]/div/div[2]/a[2]').click()
    time.sleep(1)

    # next page
    driver.find_element_by_xpath('//*[@id="tnombres1"]/p[2]/button[1]').click()

    time.sleep(2)

    hannnnndle = []
    for handle in driver.window_handles:
        hannnnndle.append(handle)
    
    time.sleep(2)

    driver.switch_to.window(driver.window_handles[1])

    html_from_page = driver.page_source
    soup = BeautifulSoup(html_from_page, 'html.parser')

    driver.quit() 
    tables = pd.read_html(html_from_page)
    Tabla  = tables[4]
    return(tables)

In [625]:
def fill():
    Total.append("")
    Total_per_1000.append("")
    Albacete.append("")
    Albacete_per_1000.append("")
    Alicante.append("")
    Alicante_per_1000.append("")
    Almería.append("")
    Almería_per_1000.append("")
    Araba.append("")
    Araba_per_1000.append("")
    Asturias.append("")
    Asturias_per_1000.append("")
    Ávila.append("")
    Ávila_per_1000.append("")
    Badajoz.append("")
    Badajoz_per_1000.append("")
    Balears_Illes.append("")
    Balears_Illes_per_1000.append("")
    Barcelona.append("")
    Barcelona_per_1000.append("")
    Bizkaia.append("")
    Bizkaia_per_1000.append("")
    Burgos.append("")
    Burgos_per_1000.append("")
    Cáceres.append("")
    Cáceres_per_1000.append("")
    Cádiz.append("")
    Cádiz_per_1000.append("")
    Cantabria.append("")
    Cantabria_per_1000.append("")
    Castellón.append("")
    Castellón_per_1000.append("")
    Ciudad_Real.append("")
    Ciudad_Real_per_1000.append("")
    Córdoba.append("")
    Córdoba_per_1000.append("")
    Coruña_A.append("")
    Coruña_A_per_1000.append("")
    Cuenca.append("")
    Cuenca_per_1000.append("")
    Gipuzkoa.append("")
    Gipuzkoa_per_1000.append("")
    Girona.append("")
    Girona_per_1000.append("")
    Granada.append("")
    Granada_per_1000.append("")
    Guadalajara.append("")
    Guadalajara_per_1000.append("")
    Huelva.append("")
    Huelva_per_1000.append("")
    Huesca.append("")
    Huesca_per_1000.append("")
    Jaén.append("")
    Jaén_per_1000.append("")
    León.append("")
    León_per_1000.append("")
    Lleida.append("")
    Lleida_per_1000.append("")
    Lugo.append("")
    Lugo_per_1000.append("")
    Madrid.append("")
    Madrid_per_1000.append("")
    Málaga.append("")
    Málaga_per_1000.append("")
    Murcia.append("")
    Murcia_per_1000.append("")
    Navarra.append("")
    Navarra_per_1000.append("")
    Ourense.append("")
    Ourense_per_1000.append("")
    Palencia.append("")
    Palencia_per_1000.append("")
    Palmas_Las.append("")
    Palmas_Las_per_1000.append("")
    Pontevedra.append("")
    Pontevedra_per_1000.append("")
    Rioja_La.append("")
    Rioja_La_per_1000.append("")
    Salamanca.append("")
    Salamanca_per_1000.append("")
    Santa_Cruz_de_Tenerife.append("")
    Santa_Cruz_de_Tenerife_per_1000.append("")
    Segovia.append("")
    Segovia_per_1000.append("")
    Sevilla.append("")
    Sevilla_per_1000.append("")
    Soria.append("")
    Soria_per_1000.append("")
    Tarragona.append("")
    Tarragona_per_1000.append("")
    Teruel.append("")
    Teruel_per_1000.append("")
    Toledo.append("")
    Toledo_per_1000.append("")
    Valencia.append("")
    Valencia_per_1000.append("")
    Valladolid.append("")
    Valladolid_per_1000.append("")
    Zamora.append("")
    Zamora_per_1000.append("")
    Zaragoza.append("")
    Zaragoza_per_1000.append("")
    Ceuta.append("")
    Ceuta_per_1000.append("")
    Melilla.append("")
    Melilla_per_1000.append("")
    Nacido_en_el_extranjero.append("")
    Nacido_en_el_extranjero_per_1000.append("")

In [788]:
def what_to_fill(category, value):
    if category == 'Total':
        Total[j] = (value)
        
    elif category == 'Total_per_1000':
        Total_per_1000[j] = (value)
        
    elif category == 'Albacete':
        Albacete[j] = (value)
        
    elif category == 'Albacete_per_1000':
        Albacete_per_1000[j] = (value)
        
    elif category == 'Alicante':
        Alicante[j] = (value)
        
    elif category == 'Alicante_per_1000':
        Alicante_per_1000[j] = (value)
        
    elif category == 'Almería':
        Almería[j] = (value)
        
    elif category == 'Almería_per_1000':
        Almería_per_1000[j] = (value)
        
    elif category == 'Araba':
        Araba[j] = (value)
        
    elif category == 'Araba_per_1000':
        Araba_per_1000[j] = (value)
    
    elif category == 'Asturias':
        Asturias[j] = (value)
        
    elif category == 'Asturias_per_1000':
        Asturias_per_1000[j] = (value)
        
    elif category == 'Ávila':
        Ávila[j] = (value)
        
    elif category == 'Ávila_per_1000':
        Ávila_per_1000[j] = (value)
        
    elif category == 'Badajoz':
        Badajoz[j] = (value)
        
    elif category == 'Badajoz_per_1000':
        Badajoz_per_1000[j] = (value)
    
    elif category == 'Balears_Illes':
        Balears_Illes[j] = (value)
        
    elif category == 'Balears_Illes_per_1000':
        Balears_Illes_per_1000[j] = (value)
        
    elif category == 'Barcelona':
        Barcelona[j] = (value)
        
    elif category == 'Barcelona_per_1000':
        Barcelona_per_1000[j] = (value)
        
    elif category == 'Bizkaia':
        Bizkaia[j] = (value)
    
    elif category == 'Bizkaia_per_1000':
        Bizkaia_per_1000[j] = (value)
        
    elif category == 'Burgos':
        Burgos[j] = (value)
        
    elif category == 'Burgos_per_1000':
        Burgos_per_1000[j] = (value)
        
    elif category == 'Cáceres':
        Cáceres[j] = (value)
    
    elif category == 'Cáceres_per_1000':
        Cáceres_per_1000[j] = (value)
        
    elif category == 'Cádiz':
        Cádiz[j] = (value)
        
    elif category == 'Cádiz_per_1000':
        Cádiz_per_1000[j] = (value)
    
    elif category == 'Cantabria':
        Cantabria[j] = (value)
        
    elif category == 'Cantabria_per_1000':
        Cantabria_per_1000[j] = (value)
        
    elif category == 'Castellón':
        Castellón[j] = (value)
        
    elif category == 'Castellón_per_1000':
        Castellón_per_1000[j] = (value)
        
    elif category == 'Ciudad_Real':
        Ciudad_Real[j] = (value)
        
    elif category == 'Ciudad_Real_per_1000':
        Ciudad_Real_per_1000[j] = (value)
        
    elif category == 'Córdoba':
        Córdoba[j] = (value)
        
    elif category == 'Córdoba_per_1000':
        Córdoba_per_1000[j] = (value)
        
    elif category == 'Coruña_A':
        Coruña_A[j] = (value)
        
    elif category == 'Coruña_A_per_1000':
        Coruña_A_per_1000[j] = (value)
        
    elif category == 'Cuenca':
        Cuenca[j] = (value)
        
    elif category == 'Cuenca_per_1000':
        Cuenca_per_1000[j] = (value)
        
    elif category == 'Gipuzkoa':
        Gipuzkoa[j] = (value)
        
    elif category == 'Gipuzkoa_per_1000':
        Gipuzkoa_per_1000[j] = (value)
        
    elif category == 'Girona':
        Girona[j] = (value)
    
    elif category == 'Girona_per_1000':
        Girona_per_1000[j] = (value)
        
    elif category == 'Granada':
        Granada[j] = (value)
    
    elif category == 'Granada_per_1000':
        Granada_per_1000[j] = (value)
        
    elif category == 'Guadalajara':
        Guadalajara[j] = (value)
    
    elif category == 'Guadalajara_per_1000':
        Guadalajara_per_1000[j] = (value)
        
    elif category == 'Huelva':
        Huelva[j] = (value)
    
    elif category == 'Huelva_per_1000':
        Huelva_per_1000[j] = (value)
        
    elif category == 'Huesca':
        Huesca[j] = (value)
        
    elif category == 'Huesca_per_1000':
        Huesca_per_1000[j] = (value)
        
    elif category == 'Jaén':
        Jaén[j] = (value)
    
    elif category == 'Jaén_per_1000':
        Jaén_per_1000[j] = (value)
        
    elif category == 'León':
        León[j] = (value)
    
    elif category == 'León_per_1000':
        León_per_1000[j] = (value)
        
    elif category == 'Lleida':
        Lleida[j] = (value)
    
    elif category == 'Lleida_per_1000':
        Lleida_per_1000[j] = (value)
        
    elif category == 'Lugo':
        Lugo[j] = (value)
        
    elif category == 'Lugo_per_1000':
        Lugo_per_1000[j] = (value)
    
    elif category == 'Madrid':
        Madrid[j] = (value)
        
    elif category == 'Madrid_per_1000':
        Madrid_per_1000[j] = (value)
    
    elif category == 'Málaga':
        Málaga[j] = (value)
        
    elif category == 'Málaga_per_1000':
        Málaga_per_1000[j] = (value)
    
    elif category == 'Murcia':
        Murcia[j] = (value)
        
    elif category == 'Murcia_per_1000':
        Murcia_per_1000[j] = (value)
    
    elif category == 'Navarra':
        Navarra[j] = (value)
        
    elif category == 'Navarra_per_1000':
        Navarra_per_1000[j] = (value)
    
    elif category == 'Ourense':
        Ourense[j] = (value)
        
    elif category == 'Ourense_per_1000':
        Ourense_per_1000[j] = (value)
    
    elif category == 'Palencia':
        Palencia[j] = (value)
        
    elif category == 'Palencia_per_1000':
        Palencia_per_1000[j] = (value)
    
    elif category == 'Palmas_Las':
        Palmas_Las[j] = (value)
        
    elif category == 'Palmas_Las_per_1000':
        Palmas_Las_per_1000[j] = (value)
    
    elif category == 'Pontevedra':
        Pontevedra[j] = (value)
        
    elif category == 'Pontevedra_per_1000':
        Pontevedra_per_1000[j] = (value)
    
    elif category == 'Rioja_La':
        Rioja_La[j] = (value)
        
    elif category == 'Rioja_La_per_1000':
        Rioja_La_per_1000[j] = (value)
    
    elif category == 'Salamanca':
        Salamanca[j] = (value)
        
    elif category == 'Salamanca_per_1000':
        Salamanca_per_1000[j] = (value)
    
    elif category == 'Santa_Cruz_de_Tenerife':
        Santa_Cruz_de_Tenerife[j] = (value)
        
    elif category == 'Santa_Cruz_de_Tenerife_per_1000':
        Santa_Cruz_de_Tenerife_per_1000[j] = (value)
    
    elif category == 'Segovia':
        Segovia[j] = (value)
        
    elif category == 'Segovia_per_1000':
        Segovia_per_1000[j] = (value)
    
    elif category == 'Sevilla':
        Sevilla[j] = (value)
    
    elif category == 'Sevilla_per_1000':
        Sevilla_per_1000[j] = (value)
        
    elif category == 'Soria':
        Soria[j] = (value)
    
    elif category == 'Soria_per_1000':
        Soria_per_1000[j] = (value)
        
    elif category == 'Tarragona':
        Tarragona[j] = (value)
    
    elif category == 'Tarragona_per_1000':
        Tarragona_per_1000[j] = (value)
        
    elif category == 'Teruel':
        Teruel[j] = (value)
        
    elif category == 'Teruel_per_1000':
        Teruel_per_1000[j] = (value)
    
    elif category == 'Toledo':
        Toledo[j] = (value)
    
    elif category == 'Toledo_per_1000':
        Toledo_per_1000[j] = (value)
        
    elif category == 'Valencia':
        Valencia[j] = (value)
    
    elif category == 'Valencia_per_1000':
        Valencia_per_1000[j] = (value)
        
    elif category == 'Valladolid':
        Valladolid[j] = (value)
    
    elif category == 'Valladolid_per_1000':
        Valladolid_per_1000[j] = (value)
        
    elif category == 'Zamora':
        Zamora[j] = (value)
        
    elif category == 'Zamora_per_1000':
        Zamora_per_1000[j] = (value)
        
    elif category == 'Zaragoza':
        Zaragoza[j] = (value)
    
    elif category == 'Zaragoza_per_1000':
        Zaragoza_per_1000[j] = (value)
    
    elif category == 'Ceuta':
        Ceuta[j] = (value)
        
    elif category == 'Ceuta_per_1000':
        Ceuta_per_1000[j] = (value)
    
    elif category == 'Melilla':
        Melilla[j] = (value)
        
    elif category == 'Melilla_per_1000':
        Melilla_per_1000[j] = (value)
    
    elif category == 'Nacido_en_el_extranjero':
        Nacido_en_el_extranjero[j] = (value)
        
    elif category == 'Nacido_en_el_extranjero_per_1000':
        Nacido_en_el_extranjero_per_1000[j] = (value)
    
    else:
        print('ERROR ', category, ' not here')

In [899]:
def Most_Popular_Surnames(Country)
    driver = webdriver.Chrome('/home/erq/chromedriver')
    Surnames = []
    url = f'https://forebears.io/{Country}/surnames'
    driver.get(url)       

    time.sleep(2)

    html_from_page = driver.page_source
    driver.close() 
    
    soup = BeautifulSoup(html_from_page, 'html.parser')
    proto_surnames = soup.find_all('td', attrs = {'class':'sur'})    

    for i in range(len(proto_surnames)):
        Surnames.append(proto_surnames[i].text)
    return(Surnames)

In [587]:
Super_Categories = []

for i in range(len(All_Categories)):
    All_Categories[i] = All_Categories[i].replace(' ','_').replace(',','').split('/')[0]
    Super_Categories.append((All_Categories[i]))
    Super_Categories.append(All_Categories[i] + ' per 1000'.replace(' ','_'))

In [646]:
# List of all the list.
Every_Category = [Total, Total_per_1000, Albacete, Albacete_per_1000, Alicante, Alicante_per_1000, Almería, Almería_per_1000, Araba, Araba_per_1000, Asturias, Asturias_per_1000, Ávila, Ávila_per_1000, Badajoz, Badajoz_per_1000, Balears_Illes, Balears_Illes_per_1000, Barcelona, Barcelona_per_1000, Bizkaia, Bizkaia_per_1000, Burgos, Burgos_per_1000, Cáceres, Cáceres_per_1000, Cádiz, Cádiz_per_1000, Cantabria, Cantabria_per_1000, Castellón, Castellón_per_1000, Ciudad_Real, Ciudad_Real_per_1000, Córdoba, Córdoba_per_1000, Coruña_A, Coruña_A_per_1000, Cuenca, Cuenca_per_1000, Gipuzkoa, Gipuzkoa_per_1000, Girona, Girona_per_1000, Granada, Granada_per_1000, Guadalajara, Guadalajara_per_1000, Huelva, Huelva_per_1000, Huesca, Huesca_per_1000, Jaén, Jaén_per_1000, León, León_per_1000, Lleida, Lleida_per_1000, Lugo, Lugo_per_1000, Madrid, Madrid_per_1000, Málaga, Málaga_per_1000, Murcia, Murcia_per_1000, Navarra, Navarra_per_1000, Ourense, Ourense_per_1000, Palencia, Palencia_per_1000, Palmas_Las, Palmas_Las_per_1000, Pontevedra, Pontevedra_per_1000, Rioja_La, Rioja_La_per_1000, Salamanca, Salamanca_per_1000, Santa_Cruz_de_Tenerife, Santa_Cruz_de_Tenerife_per_1000, Segovia, Segovia_per_1000, Sevilla, Sevilla_per_1000, Soria, Soria_per_1000, Tarragona, Tarragona_per_1000, Teruel, Teruel_per_1000, Toledo, Toledo_per_1000, Valencia, Valencia_per_1000, Valladolid, Valladolid_per_1000, Zamora, Zamora_per_1000, Zaragoza, Zaragoza_per_1000, Ceuta, Ceuta_per_1000, Melilla, Melilla_per_1000, Nacido_en_el_extranjero, Nacido_en_el_extranjero_per_1000]

In [ ]:
# This next cell is the main one in the program, it scrapes the INE database and forms the dataframe

In [929]:
#Nombres = ['Rodriguez', 'Mikelarena']
Nombres = Apellidos[:]
Origins = []
Tablas = []
Origin_Search = []
for i in range(len(Apellidos)):
    if 'ñ' in Apellidos[i]:
        Origin_Search.append((Apellidos[i].replace('ñ','%F1')))
        
Total, Total_per_1000, Albacete, Albacete_per_1000, Alicante, Alicante_per_1000, Almería, Almería_per_1000, Araba, Araba_per_1000, Asturias, Asturias_per_1000, Ávila, Ávila_per_1000, Badajoz, Badajoz_per_1000, Balears_Illes, Balears_Illes_per_1000, Barcelona, Barcelona_per_1000, Bizkaia, Bizkaia_per_1000, Burgos, Burgos_per_1000, Cáceres, Cáceres_per_1000, Cádiz, Cádiz_per_1000, Cantabria, Cantabria_per_1000, Castellón, Castellón_per_1000, Ciudad_Real, Ciudad_Real_per_1000, Córdoba, Córdoba_per_1000, Coruña_A, Coruña_A_per_1000, Cuenca, Cuenca_per_1000, Gipuzkoa, Gipuzkoa_per_1000, Girona, Girona_per_1000, Granada, Granada_per_1000, Guadalajara, Guadalajara_per_1000, Huelva, Huelva_per_1000, Huesca, Huesca_per_1000, Jaén, Jaén_per_1000, León, León_per_1000, Lleida, Lleida_per_1000, Lugo, Lugo_per_1000, Madrid, Madrid_per_1000, Málaga, Málaga_per_1000, Murcia, Murcia_per_1000, Navarra, Navarra_per_1000, Ourense, Ourense_per_1000, Palencia, Palencia_per_1000, Palmas_Las, Palmas_Las_per_1000, Pontevedra, Pontevedra_per_1000, Rioja_La, Rioja_La_per_1000, Salamanca, Salamanca_per_1000, Santa_Cruz_de_Tenerife, Santa_Cruz_de_Tenerife_per_1000, Segovia, Segovia_per_1000, Sevilla, Sevilla_per_1000, Soria, Soria_per_1000, Tarragona, Tarragona_per_1000, Teruel, Teruel_per_1000, Toledo, Toledo_per_1000, Valencia, Valencia_per_1000, Valladolid, Valladolid_per_1000, Zamora, Zamora_per_1000, Zaragoza, Zaragoza_per_1000, Ceuta, Ceuta_per_1000, Melilla, Melilla_per_1000, Nacido_en_el_extranjero, Nacido_en_el_extranjero_per_1000 = ([] for i in range(108))
for j in range(len(Nombres)):
    
    print(Nombres[j]) 
    
    fill()
   
    Origins.append(Origin(Origin_Search[j]))
    
    Tabla = Surname_Data(Nombres[j])
    Tablas.append(Tabla)
    
    for i in range(len(Tabla['Provincia']['Provincia'])):
        provincia = Tabla['Provincia']['Provincia'][i]
        
        category = provincia.replace(' ','_').replace(',','').split('/')[0]

        category_1000 = category + ' per 1000'.replace(' ','_')

        try:
            #This gets the value of the Frequency per 1000 value on the correct format
            
            Fix_Format_per_mil = str(Tabla['Apellido 1º']['Por mil\xa0(‰)'][i])
            Value_1 = float(Fix_Format_per_mil[:-3] + '.'+ Fix_Format_per_mil[-3:])
            Fix_Format_per_mil = str(Tabla['Apellido 2º']['Por mil\xa0(‰)'][i])
            Value_2 = float(Fix_Format_per_mil[:-3] + '.'+ Fix_Format_per_mil[-3:]) 
        
            Value_per_mil = (Value_1 + Value_2)/2
            
            what_to_fill(category_1000, Value_per_mil)
            
        except:
            pass
        
        if len(str(Tabla['Apellido 1º']['Total'][i]).replace('.','')) > 7:
            
            Value_1 = int((str(Tabla['Apellido 1º']['Total'][i]).split('.')[0])+(str(Tabla['Apellido 1º']['Total'][i]).split('.')[1][:3]))
           
            Total_number = Value_1 + Value_2
        
        elif len(str(Tabla['Apellido 1º']['Total'][i]).split(".")[-1]) == 2:
            Value_1 = int(str((Tabla['Apellido 1º']['Total'][i])).replace('.','')+'0')
        
        else: 
            Value_1 = int(str(Tabla['Apellido 1º']['Total'][i]).replace('.',''))

        if len(str(Tabla['Apellido 2º']['Total'][i]).replace('.','')) > 7:
            
            Value_2 = int((str(Tabla['Apellido 2º']['Total'][i]).split('.')[0])+(str(Tabla['Apellido 2º']['Total'][i]).split('.')[1][:3]))
           
        elif len(str(Tabla['Apellido 2º']['Total'][i]).split(".")[-1]) == 2:
            Value_2 = int(str((Tabla['Apellido 2º']['Total'][i])).replace('.','')+'0')
        else: 
            Value_2 = int(str(Tabla['Apellido 2º']['Total'][i]).replace('.',''))
            
        Total_Value = Value_1 + Value_2

        what_to_fill(category, Total_Value)

Dataset = pd.DataFrame()
Dataset['Name/Surname'] = Nombres
Dataset['Type'] = ""
Dataset['Name_Origin'] = Origins
Dataset['Religion'] = ""
Dataset['Type'] = ""
Dataset['Average Age'] = ""

Every_Category = [Total, Total_per_1000, Albacete, Albacete_per_1000, Alicante, Alicante_per_1000, Almería, Almería_per_1000, Araba, Araba_per_1000, Asturias, Asturias_per_1000, Ávila, Ávila_per_1000, Badajoz, Badajoz_per_1000, Balears_Illes, Balears_Illes_per_1000, Barcelona, Barcelona_per_1000, Bizkaia, Bizkaia_per_1000, Burgos, Burgos_per_1000, Cáceres, Cáceres_per_1000, Cádiz, Cádiz_per_1000, Cantabria, Cantabria_per_1000, Castellón, Castellón_per_1000, Ciudad_Real, Ciudad_Real_per_1000, Córdoba, Córdoba_per_1000, Coruña_A, Coruña_A_per_1000, Cuenca, Cuenca_per_1000, Gipuzkoa, Gipuzkoa_per_1000, Girona, Girona_per_1000, Granada, Granada_per_1000, Guadalajara, Guadalajara_per_1000, Huelva, Huelva_per_1000, Huesca, Huesca_per_1000, Jaén, Jaén_per_1000, León, León_per_1000, Lleida, Lleida_per_1000, Lugo, Lugo_per_1000, Madrid, Madrid_per_1000, Málaga, Málaga_per_1000, Murcia, Murcia_per_1000, Navarra, Navarra_per_1000, Ourense, Ourense_per_1000, Palencia, Palencia_per_1000, Palmas_Las, Palmas_Las_per_1000, Pontevedra, Pontevedra_per_1000, Rioja_La, Rioja_La_per_1000, Salamanca, Salamanca_per_1000, Santa_Cruz_de_Tenerife, Santa_Cruz_de_Tenerife_per_1000, Segovia, Segovia_per_1000, Sevilla, Sevilla_per_1000, Soria, Soria_per_1000, Tarragona, Tarragona_per_1000, Teruel, Teruel_per_1000, Toledo, Toledo_per_1000, Valencia, Valencia_per_1000, Valladolid, Valladolid_per_1000, Zamora, Zamora_per_1000, Zaragoza, Zaragoza_per_1000, Ceuta, Ceuta_per_1000, Melilla, Melilla_per_1000, Nacido_en_el_extranjero, Nacido_en_el_extranjero_per_1000]

All_Categories = []
for i in range(len(Super_Categories)):
    Category = Super_Categories[i]
    Dataset[Category] = Every_Category[i]

Garcia
Muñoz
No es el primero
Muñoz de Morales
No es el primero
Muñoz de Otálora
No es el primero
Muñoz de Robles
No es el primero
muÑoza
No es el primero
Origin not found for Mu%F1oz
31.533 Total_per_1000
['']
Rodriguez
inuÑez
No es el primero
Nuñez
No es el primero
Vasco Nuñez de Balboa
No es el primero
Origin not found for Nu%F1ez
19.9025 Total_per_1000
[2946636, '']
Gonzalez
De la Peña
No es el primero
Fernández de la peña
No es el primero
García de la peña
No es el primero
Gómez de la peña
No es el primero
González de la peña
No es el primero
Origin not found for Pe%F1a
19.886000000000003 Total_per_1000
[2946636, 1859850, '']
Fernandez
Ibañez
No es el primero
peribaÑez
No es el primero
ramiro damian ibañez
No es el primero
santibáñez
No es el primero
Origin not found for Iba%F1ez
19.674 Total_per_1000
[2946636, 1859850, 1858265, '']
Lopez
Castaño
No es el primero
castaÑon
No es el primero
castaÑondo
No es el primero
Castaños
No es el primero
castaÑosa
No es el primero
Origin not found for Casta%F1o
18.6945 Total_per_1000
[2946636, 1859850, 1858265, 1838439, '']
Martinez
Díaz ordóñez
No es el primero
Marín Ordóñez
No es el primero
Ordoñez
No es el primero
Origin not found for Ordo%F1ez
17.874499999999998 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, '']
Sanchez
Piñeiro
No es el primero
piÑeiroa
No es el primero
Origin not found for Pi%F1eiro
17.573 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, '']
Perez
Muñiz
No es el primero
Origin not found for Mu%F1iz
16.7785 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, '']
Gomez
cocaÑa
No es el primero
Ocaña
No es el primero
Origin not found for Oca%F1a
10.552 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, '']
Martin
Piñero
No es el primero
piÑeros
No es el primero
Origin not found for Pi%F1ero
10.4235 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, '']
Jimenez
Carreño
No es el primero
Origin not found for Carre%F1o
8.435500000000001 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, '']
Ruiz
Castañeda
No es el primero
García de castañeda
No es el primero
Origin not found for Casta%F1eda
7.9005 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, '']
Hernandez
ÑaÑez
No es el primero
Yáñez
No es el primero
Origin not found for Ya%F1ez
7.795 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, '']
Diaz
alcaÑas
No es el primero
Cañas
No es el primero
caÑasveras
No es el primero
marcial cañas
No es el primero
Valdecañas
No es el primero
Origin not found for Ca%F1as
7.2755 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, '']
Moreno
Baños
No es el primero
tolbaÑos
No es el primero
Origin not found for Ba%F1os
6.872999999999999 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, '']
Muñoz
Patiño
No es el primero
Origin not found for Pati%F1o
6.0385 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, '']
Alvarez
Peñalver
No es el primero
peÑalvert
No es el primero
Origin not found for Pe%F1alver
5.999499999999999 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, '']
Romero
fortuÑo
No es el primero
Ortuño
No es el primero
Origin not found for Ortu%F1o
4.7330000000000005 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, 560651, '']
Alonso
BeleÑo
No es el primero
calcurian
No es el primero
España
No es el primero
espaÑadero
No es el primero
Españán
No es el primero
Origin not found for Espa%F1a
4.181 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, 560651, 442308, '']
Gutierrez
Viñas
No es el primero
Origin not found for Vi%F1as
4.18 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, 560651, 442308, 390719, '']
Navarro
Baldueñas
No es el primero
Dueñas
No es el primero
Endueñas
No es el primero
Garcidueñas
No es el primero
Origin not found for Due%F1as
3.784 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, 560651, 442308, 390719, 390600, '']
Torres
Bolaños
No es el primero
Origin not found for Bola%F1os
3.618 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, 560651, 442308, 390719, 390600, 353606, '']
Dominguez
Montaño
No es el primero
montaÑola
No es el primero
Origin not found for Monta%F1o
3.3855 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, 560651, 442308, 390719, 390600, 353606, 338068, '']
Ramos
García mariño
No es el primero
marinho
No es el primero
Mariño
No es el primero
Mariños
No es el primero
mariÑosa
No es el primero
Origin not found for Mari%F1o
3.0919999999999996 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, 560651, 442308, 390719, 390600, 353606, 338068, 159158, '']
Vazquez
Acuña
No es el primero
acuÑas
No es el primero
dacuña
No es el primero
González de acuña
No es el primero
Gutiérrez de acuña
No es el primero
Origin not found for Acu%F1a
3.1455 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, 560651, 442308, 390719, 390600, 353606, 338068, 159158, 288895, '']
Gil
Cañete
No es el primero
Escañete
No es el primero
Origin not found for Ca%F1ete
2.9924999999999997 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, 560651, 442308, 390719, 390600, 353606, 338068, 159158, 288895, 293904, '']
Ramirez
Fariña
No es el primero
fariÑas
No es el primero
Origin not found for Fari%F1a
2.944 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, 560651, 442308, 390719, 390600, 353606, 338068, 159158, 288895, 293904, 279608, '']
Serrano
Gureña
No es el primero
Ureña
No es el primero
Origin not found for Ure%F1a
2.819 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, 560651, 442308, 390719, 390600, 353606, 338068, 159158, 288895, 293904, 279608, 275117, '']
Blanco
cañadas
No es el primero
Origin not found for Ca%F1adas
2.6245000000000003 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, 560651, 442308, 390719, 390600, 353606, 338068, 159158, 288895, 293904, 279608, 275117, 263427, '']
Molina
cegoÑino
No es el primero
Goñi
No es el primero
Origin not found for Go%F1i
2.6035000000000004 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, 560651, 442308, 390719, 390600, 353606, 338068, 159158, 288895, 293904, 279608, 275117, 263427, 245215, '']
Morales
Caamaño
No es el primero
Origin not found for Caama%F1o
2.588 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, 560651, 442308, 390719, 390600, 353606, 338068, 159158, 288895, 293904, 279608, 275117, 263427, 245215, 243255, '']

Suarez
Cañizares
No es el primero
Origin not found for Ca%F1izares
2.5805 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, 560651, 442308, 390719, 390600, 353606, 338068, 159158, 288895, 293904, 279608, 275117, 263427, 245215, 243255, 241819, '']
Ortega
camaÑas
No es el primero
Mañas
No es el primero
omaÑas
No es el primero
valimaÑas
No es el primero
Origin not found for Ma%F1as
2.5084999999999997 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, 560651, 442308, 390719, 390600, 353606, 338068, 159158, 288895, 293904, 279608, 275117, 263427, 245215, 243255, 241819, 241130, '']
Delgado
Quiñones
No es el primero
Vigil de Quiñones
No es el primero
Origin not found for Qui%F1ones
2.498 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, 560651, 442308, 390719, 390600, 353606, 338068, 159158, 288895, 293904, 279608, 275117, 263427, 245215, 243255, 241819, 241130, 234408, '']
Castro
Saldaña
No es el primero
Origin not found for Salda%F1a
2.4845 Total_per_1000
[2946636, 1859850, 1858265, 1838439, 1746920, 1670288, 1642124, 1567851, 986046, 974031, 788241, 738283, 728415, 679848, 642292, 564303, 560651, 442308, 390719, 390600, 353606, 338068, 159158, 288895, 293904, 279608, 275117, 263427, 245215, 243255, 241819, 241130, 234408, 233401, '']
Ortiz

IndexError: list index out of range

In [911]:
Dataset

,Name/Surname,Type,Name_Origin,Religion,Average Age,Total,Total_per_1000,Albacete,Albacete_per_1000,Alicante,...,Zamora,Zamora_per_1000,Zaragoza,Zaragoza_per_1000,Ceuta,Ceuta_per_1000,Melilla,Melilla_per_1000,Nacido_en_el_extranjero,Nacido_en_el_extranjero_per_1000
0,Garcia,,,,,2946636,31.5330,60877,63.3870,86995,...,19466,35.5580,39694,25.1495,4398,24.2080,5059,26.8060,101803,7.9595
1,Rodriguez,,Spain,,,1859850,19.9025,12808,13.3360,29211,...,21624,39.5000,8563,5.4260,2938,16.1715,2576,13.6495,108907,8.5155
2,Gonzalez,,,,,1858265,19.8860,25017,26.0485,24861,...,15300,27.9500,11703,7.4150,2824,15.5445,2611,13.8405,93883,7.3405
3,Fernandez,,,,,1838439,19.6740,18784,19.5585,27209,...,20746,37.8960,9908,6.2775,2342,12.8910,2793,14.7990,58580,4.5800
4,Lopez,,,,,1746920,18.6945,40221,41.8795,45625,...,6975,12.7430,22646,14.3485,2756,15.1700,3881,20.5645,78145,6.1100
5,Martinez,,Spain,,,1670288,17.8745,58832,61.2580,86670,...,6856,12.5240,27860,17.6520,13420,7.3870,3192,16.9135,71313,5.5755
6,Sanchez,,,,,1642124,17.5730,38946,40.5520,47438,...,6654,12.1545,20484,12.9785,3160,17.3990,2844,15.0695,67556,5.2820
7,Perez,,,,,1567851,16.7785,14669,15.2740,57105,...,14264,26.0555,27584,17.4770,2633,14.4925,2826,14.9745,77039,6.0235
8,Gomez,,,,,986046,10.5520,20253,21.0880,22423,...,4260,7.7815,12308,7.7980,14580,8.0255,13670,7.2435,47981,3.7515
9,Martin,,,,,974031,10.4235,9150,0.9530,5744,...,16701,30.5070,11335,7.1815,18530,10.1995,16210,8.5890,18499,1.4465
10,Jimenez,,,,,788241,8.4355,15985,16.6440,9794,...,2134,3.8980,9806,6.2140,16650,9.1645,17760,9.4105,31215,2.4410
11,Ruiz,,Spain,,,738283,7.9005,11575,12.0520,22471,...,10860,1.9835,10168,6.4425,16460,9.0600,2196,11.6360,26584,2.0785
12,Hernandez,,Spain,,,728415,7.7950,6809,7.0895,21814,...,8799,16.0725,12572,7.9655,6270,3.4515,12440,6.5920,49217,3.8480
13,Diaz,,,,,679848,7.2755,7165,7.4615,10409,...,4100,0.7490,3818,2.4190,10980,6.0440,12860,6.8145,44519,3.4810
14,Moreno,,Spain,,,642292,6.8730,16545,17.2270,16708,...,8250,1.5070,8588,5.4410,10860,5.9780,11930,6.3210,21502,1.6810